Repository EFUB-GeumJaSsi/GiftU-Front, pull requests merged in 2024-07, with the labels that each got.

#1 Delete pull_request_template.md
  pull_request_template.md
Labels: Docs 📃

#2 Create pull_request_template.md
  pull_request_template.md
Labels: Docs 📃

#3 1주차 조아령 | 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: Docs 📃

#4 1주차 성혜린 | 프로젝트 초기 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  public/favicon.svg
  public/index.html
  src/App.js
  src/api/client.js
  src/assets/Login/logo.svg
  src/assets/common/NavigationBar/icn_home.svg
  src/components/Notification/NotiItem.jsx
  src/components/common/Modal.jsx
  src/global.css
  src/index.js
  src/pages/Friend/FriendPage.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/CompletePage.jsx
  src/pages/FundingJoin/FundingJoinPage.jsx
  src/pages/FundingOpen/CompletePage.jsx
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/GiftAddPage.jsx
  src/pages/FundingOpen/GiftSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Home/SearchPage.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/My/MyPage.jsx
  src/pages/MyJoinFunding/ItemPage.jsx
  src/pages/MyJoinFunding/ListPage.jsx
  src/pages/MyJoinFunding/ReviewEditPage.jsx
  src/pages/MyOpenFunding/ItemPage.jsx
  src/pages/MyOpenFunding/ListPage.jsx
  src/pages/MyOpenFunding/MessageEditPage.jsx
  src/pages/Notification/NotificationPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
  src/pages/Tutorial/TutorialPage.jsx
  src/reset.css
Labels: Settings ⚙️

#6 1주차 | dev 브랜치 머지
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  public/favicon.svg
  public/index.html
  pull_request_template.md
  src/App.js
  src/api/client.js
  src/assets/Login/logo.svg
  src/assets/common/NavigationBar/icn_home.svg
  src/components/Notification/NotiItem.jsx
  src/components/common/Modal.jsx
  src/global.css
  src/index.js
  src/pages/Friend/FriendPage.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/CompletePage.jsx
  src/pages/FundingJoin/FundingJoinPage.jsx
  src/pages/FundingOpen/CompletePage.jsx
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/GiftAddPage.jsx
  src/pages/FundingOpen/GiftSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Home/SearchPage.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/My/MyPage.jsx
  src/pages/MyJoinFunding/ItemPage.jsx
  src/pages/MyJoinFunding/ListPage.jsx
  src/pages/MyJoinFunding/ReviewEditPage.jsx
  src/pages/MyOpenFunding/ItemPage.jsx
  src/pages/MyOpenFunding/ListPage.jsx
  src/pages/MyOpenFunding/MessageEditPage.jsx
  src/pages/Notification/NotificationPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
  src/pages/Tutorial/TutorialPage.jsx
  src/reset.css
Labels: Docs 📃, Settings ⚙️

#16 1주차 | 로그인 페이지, 모달 컴포넌트 퍼블리싱
  public/index.html
  src/assets/Login/giftu_logo.svg
  src/assets/Login/kakao_logo.svg
  src/components/common/Modal.jsx
  src/pages/Login/LoginPage.jsx
Labels: UI 💄

#10 1주차 | 공통 컴포넌트 뒤로가기 헤더 및 버튼 퍼블리싱
  src/assets/common/btn_back.svg
  src/components/common/BackHeader.jsx
  src/components/common/Button.jsx
Labels: UI 💄

#14 1주차 | NavBar 퍼블리싱
  src/App.js
  src/assets/common/NavigationBar/grey_icn_alarm.svg
  src/assets/common/NavigationBar/grey_icn_friend.svg
  src/assets/common/NavigationBar/grey_icn_home.svg
  src/assets/common/NavigationBar/grey_icn_mypage.svg
  src/assets/common/NavigationBar/grey_icn_present.svg
  src/assets/common/NavigationBar/icn_alarm.svg
  src/assets/common/NavigationBar/icn_friend.svg
  src/assets/common/NavigationBar/icn_home.svg
  src/assets/common/NavigationBar/icn_mypage.svg
  src/assets/common/NavigationBar/icn_present.svg
  src/components/common/Nav.jsx
Labels: UI 💄

#17 1주차 | global.css 수정 및 코드 리팩토링, 웹페이지 언어 수정
  public/index.html
  src/components/common/Button.jsx
  src/components/common/Modal.jsx
  src/global.css
  src/pages/Login/LoginPage.jsx
Labels: UI 💄, Refactor ♻️

#15 1주차 | 태그 구분 컴포넌트 및 알림페이지 퍼블리싱
  src/components/Notification/NotiItem.jsx
  src/components/Notification/NotificationItem.jsx
  src/components/common/NotiItem.jsx
  src/pages/Notification/NotificationPage.jsx
Labels: UI 💄

#22 1주차 | 패키지 설치, 코드 리팩토링
  package-lock.json
  package.json
  src/pages/Login/LoginPage.jsx
  src/pages/Notification/NotificationPage.jsx
Labels: Settings ⚙️, Refactor ♻️

#31 2주차 | 검색페이지 및 프로필 수정 페이지 퍼블리싱
  src/assets/common/calendar.svg
  src/assets/common/camera.svg
  src/assets/common/search.svg
  src/components/Home/SearchResults.jsx
  src/components/Notification/NotificationItemComponent.jsx
  src/components/common/NotiItem.jsx
  src/pages/Home/SearchPage.jsx
  src/pages/Notification/NotificationPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
Labels: UI 💄

#32 2주차 | 펀딩 상세 페이지 퍼블리싱
  src/assets/FundingInfo/fold 1.svg
  src/assets/FundingInfo/icn_back.svg
  src/components/FundingInfo/CongratsMessage.jsx
  src/components/FundingInfo/FundingComment.jsx
  src/components/FundingInfo/FundingParticipants.jsx
  src/components/FundingInfo/FundingPercentage.jsx
  src/components/FundingInfo/FundingSpan.jsx
  src/components/FundingInfo/GoWriteButton.jsx
  src/components/FundingInfo/TopFundingInfo.jsx
  src/components/common/BackHeader.jsx
  src/components/common/BottomBackground.jsx
  src/components/common/Button.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/reset.css
Labels: UI 💄

#55 3주차 | 패스워드, 펀딩세팅 페이지 퍼블리싱
  src/App.js
  src/assets/PasswordSet/icn_btn_no.svg
  src/assets/PasswordSet/icn_btn_yes.svg
  src/global.css
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
  src/pages/ListPage.jsx
  src/pages/MyJoinFunding/ListJoinPage.jsx
  src/pages/MyOpenFunding/ListOpenPage.jsx
  src/pages/MyOpenFunding/ListPage.jsx
Labels: UI 💄, Refactor ♻️

#57 3주차 | 모달 컴포넌트, 홈 페이지, 펀딩 개설>선물 정보입력 페이지, 펀딩 개설>완료 페이지 퍼블리싱
  src/assets/FungingOpen/icn_gift.svg
  src/assets/FungingOpen/icn_plus.svg
  src/components/common/CompletePageComponent.jsx
  src/components/common/ModalComponent.jsx
  src/components/common/PriceInputComponent.jsx
  src/pages/FundingOpen/CompletePage.jsx
  src/pages/FundingOpen/GiftSetPage.jsx
  src/pages/Home/HomePage.jsx
Labels: UI 💄

#56 3주차 | 펀딩 참여 페이지, 펀딩 참여 완료 페이지, 선물 추가 페이지 퍼블리싱 및 펀딩 상세 페이지 분기 수정, 캘린더 컴포넌트 퍼블리싱
  package-lock.json
  package.json
  src/assets/FundingJoin/btn_radio_off.svg
  src/assets/FundingJoin/btn_radio_on.svg
  src/assets/FundingJoin/gift_icon.svg
  src/assets/Home/tag_today.svg
  src/components/FundingInfo/FundingPercentage.jsx
  src/components/FundingInfo/GoWriteButton.jsx
  src/components/Home/Calendar.jsx
  src/components/Home/CalendarFundingItem.jsx
  src/components/common/BottomBackground.jsx
  src/components/common/ButtonComponent.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/CompletePage.jsx
  src/pages/FundingJoin/FundingJoinPage.jsx
  src/pages/FundingOpen/GiftAddPage.jsx
Labels: UI 💄, Refactor ♻️

#54 3주차 | 축하메세지 수정 페이지, 선물후기 작성 페이지, 튜토리얼 페이지 퍼블리싱, 2주차 수정사항 반영
  src/assets/Tutorial/btn_drop.svg
  src/assets/Tutorial/fnd_slider.svg
  src/assets/Tutorial/fnd_slider2.svg
  src/assets/Tutorial/icon_pw_no.svg
  src/assets/Tutorial/icon_pw_yes.svg
  src/assets/Tutorial/logo.svg
  src/assets/Tutorial/present.svg
  src/components/Home/SearchResults.jsx
  src/components/Notification/NotificationItem.jsx
  src/components/Tutorial/TitleDescription.jsx
  src/components/common/TagSelectComponent.jsx
  src/pages/Home/SearchPage.jsx
  src/pages/MyJoinFunding/ReviewEditPage.jsx
  src/pages/MyOpenFunding/MessageEditPage.jsx
  src/pages/Notification/NotificationPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
  src/pages/Tutorial/TutorialPage.jsx
Labels: UI 💄, Refactor ♻️

#58 3주차 수정사항 반영 | 비밀번호 컴포넌트 분리
  src/App.js
  src/components/common/PasswordComponent.jsx
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
Labels: UI 💄, Refactor ♻️

#61 4주차 | 코드리뷰 반영
  src/components/Tutorial/TitleDescription.jsx
  src/pages/Edit/MessageEditPage.jsx
  src/pages/Edit/ReviewEditPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
Labels: Refactor ♻️

#75 4주차 | API 연결 사전작업, 라우팅 주소 설정
  src/App.js
  src/api/api.js
  src/api/calendar.js
  src/api/client.js
  src/api/example.js
  src/api/friend.js
  src/api/funding.js
  src/api/notice.js
  src/api/oauth.js
  src/api/review.js
  src/api/search.js
  src/api/user.js
  src/assets/common/icn_loading.svg
  src/components/Friend/HorizontalCard.jsx
  src/components/Friend/VerticalCard.jsx
  src/components/common/SpinnerComponent.jsx
  src/components/common/ToastComponent.jsx
  src/pages/Friend/FriendPage.jsx
  src/pages/FundingJoin/IndexPage.jsx
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/IndexPage.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/Login/OAuthRedirectPage.jsx
Labels: Settings ⚙️, UI 💄, Refactor ♻️, Feature ✨

#71 4주차 | api 작업 전 퍼블리싱 정리
  src/assets/FungingOpen/delete_btn.svg
  src/components/FundingInfo/FundingParticipants.jsx
  src/components/FundingInfo/FundingPercentage.jsx
  src/components/FundingInfo/PriceProgressBar.jsx
  src/components/Home/CalendarFundingItem.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/CompletePage.jsx
  src/pages/FundingJoin/FundingJoinPage.jsx
  src/pages/FundingOpen/GiftAddPage.jsx
Labels: Refactor ♻️

#70 4주차 | 오류 수정, 프로필이미지 추가, 셀프 클로징
  src/assets/common/profile.svg
  src/components/Notification/NotificationItem.jsx
  src/components/Tutorial/TitleDescription.jsx
  src/components/common/TagSelectComponent.jsx
  src/pages/Edit/MessageEditPage.jsx
  src/pages/Edit/ReviewEditPage.jsx
  src/pages/Notification/NotificationPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
  src/pages/Search/SearchPage.jsx
  src/pages/Tutorial/TutorialPage.jsx
Labels: UI 💄, Refactor ♻️

#65 4주차 | fundingComponent/List 수정, 주소 api연결
  package-lock.json
  package.json
  src/assets/My/icn_profile.svg
  src/components/common/FundingComponent.jsx
  src/components/common/PasswordComponent.jsx
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
  src/pages/List/ListJoinPage.jsx
  src/pages/List/ListOpenPage.jsx
  src/pages/List/ListPage.jsx
  src/pages/My/MyPage.jsx
Labels: UI 💄, Refactor ♻️, Feature ✨

#79 4주차 | 퍼블리싱 정리, calendar.js user.js 작성
  src/api/calendar.js
  src/api/user.js
  src/assets/FungingOpen/delete_btn.svg
  src/components/FundingInfo/CongratsMessage.jsx
  src/components/FundingInfo/DeleteBtn.jsx
  src/components/FundingInfo/FundingComment.jsx
  src/components/FundingInfo/FundingParticipants.jsx
  src/components/FundingInfo/FundingPercentage.jsx
  src/components/FundingInfo/FundingSpan.jsx
  src/components/FundingInfo/GoWriteButton.jsx
  src/components/FundingInfo/PriceProgressBar.jsx
  src/components/FundingInfo/TopFundingInfo.jsx
  src/components/FundingInfo/stylefunction.js
  src/components/Home/Calendar.jsx
  src/components/common/BackHeaderComponent.jsx
  src/components/common/ButtonComponent.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/FundingJoinPage.jsx
Labels: Refactor ♻️, Feature ✨

#81 4주차 | API 연결 및 수정사항 반영
  src/api/notice.js
  src/api/review.js
  src/api/search.js
  src/pages/Edit/MessageEditPage.jsx
  src/pages/Notification/NotificationPage.jsx
Labels: Refactor ♻️, Feature ✨

#80 4주차 | api hook 연결, 수정사항 반영
  src/api/funding.js
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
  src/pages/My/MyPage.jsx
Labels: Refactor ♻️, Feature ✨

#82 5주차 | 완료 페이지 컴포넌트 수직중앙정렬 수정
  src/components/common/CompletePageComponent.jsx
Labels: UI 💄

#85 4주차 | 필요 페이지에 네비게이션바 및 BottomBackground 추가, 주차별 코드 리팩토링
  src/assets/My/icn_profile.svg
  src/assets/common/profile_default.svg
  src/components/FundingInfo/FundingParticipants.jsx
  src/components/Notification/NotificationItem.jsx
  src/components/Search/SearchResults.jsx
  src/components/common/BottomBackgroundComponent.jsx
  src/components/common/NavComponent.jsx
  src/global.css
  src/pages/Friend/FriendPage.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/CompletePage.jsx
  src/pages/FundingOpen/CompletePage.jsx
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/GiftAddPage.jsx
  src/pages/FundingOpen/GiftSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
  src/pages/Home/HomePage.jsx
  src/pages/List/ListPage.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/Login/OAuthRedirectPage.jsx
  src/pages/My/MyPage.jsx
  src/pages/Notification/NotificationPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
  src/pages/Search/SearchPage.jsx
Labels: Settings ⚙️, UI 💄, Refactor ♻️

#87 5주차 | 최근 내 펀딩에 참여한 친구 조회 API 요청 Hook
  src/api/friend.js
  src/api/oauth.js
  src/api/review.js
  src/api/search.js
  src/components/Friend/HorizontalCard.jsx
  src/pages/Login/OAuthRedirectPage.jsx
Labels: Refactor ♻️, Feature ✨

#86 5주차 | NavbarBar수정, PasswordComponent수정, funding.js수정
  src/api/funding.js
  src/assets/common/NavigationBar/icn_alarm.svg
  src/components/common/NavComponent.jsx
  src/components/common/PasswordComponent.jsx
Labels: Refactor ♻️, Feature ✨
