Repository EFUB-GeumJaSsi/GiftU-Front, pull requests merged in 2024-09, with the labels that each got.

#149 8주차 | 알림페이지 및 튜토리얼 페이지 수정
  src/pages/Notification/NotificationPage.jsx
  src/pages/Tutorial/TutorialPage.jsx
Labels: Bug 🐞, UI 💄

#143 8주차 | 전화번호 검증기능 추가
  src/pages/FundingOpen/FundingSetPage.jsx
Labels: Feature ✨

#137 7주차 | 토스트 컴포넌트 퍼블리싱, 펀딩 개설 IndexPage 버그 수정, 그외 코드 리팩토링
  .github/workflows/branch-management.yml
  src/components/Friend/HorizontalCard.jsx
  src/components/List/List.jsx
  src/components/Notification/NotificationItem.jsx
  src/components/common/BottomModalComponent.jsx
  src/components/common/BottomSheetComponent.jsx
  src/components/common/DialogComponent.jsx
  src/components/common/SlideUpModalComponent.jsx
  src/components/common/TagFilterComponent.jsx
  src/components/common/ToastComponent.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingOpen/IndexPage.jsx
  src/pages/Notification/NotificationPage.jsx
Labels: Docs 📃, UI 💄, Refactor ♻️, Fix🔧
