Repository EFUB-GeumJaSsi/GiftU-Front, pull requests merged in 2024-08, with the labels that each got.

#88 5주차 | fundingList, MyPage GET
  src/api/funding.js
  src/pages/List/ListJoinPage.jsx
  src/pages/List/ListOpenPage.jsx
  src/pages/My/MyPage.jsx
Labels: Refactor ♻️, Feature ✨

#92 5주차 | 검색페이지, 선물후기 수정페이지 API 연결
  src/api/search.js
  src/pages/Edit/ReviewEditPage.jsx
  src/pages/Search/SearchPage.jsx
Labels: Feature ✨

#93 5주차 | 펀딩 상세 페이지, 펀딩 참여 페이지 api 연결
  src/components/FundingInfo/CongratsMessage.jsx
  src/components/FundingInfo/FundingComment.jsx
  src/components/FundingInfo/FundingParticipants.jsx
  src/components/FundingInfo/FundingPercentage.jsx
  src/components/FundingInfo/FundingSpan.jsx
  src/components/FundingInfo/GoWriteButton.jsx
  src/components/FundingInfo/PriceProgressBar.jsx
  src/components/FundingInfo/TopFundingInfo.jsx
  src/components/FundingInfo/stylefunction.js
  src/components/common/PasswordComponent.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/FundingJoinPage.jsx
Labels: Refactor ♻️, Feature ✨

#95 5주차 | 펀딩 개설 > 펀딩 정보입력 페이지, 비밀번호 설정 페이지 오류 해결
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
Labels: Refactor ♻️

#107 5주차 | 폰트 공통스타일 추가, 친구페이지 프로필사진기본이미지 설정, 4·5주차 디자인 수정사항 반영, 라우팅 인증/인가 HOC, 최근내펀딩에참여한친구·참여가능한펀딩 API 연결, 그외 코드리팩토링
  src/App.js
  src/api/api.js
  src/api/oauth.js
  src/components/Friend/HorizontalCard.jsx
  src/components/Friend/VerticalCard.jsx
  src/components/Home/Calendar.jsx
  src/components/common/CarouselComponent.jsx
  src/hoc/Auth.jsx
  src/index.js
  src/pages/Friend/FriendPage.jsx
  src/pages/FundingOpen/CompletePage.jsx
  src/pages/FundingOpen/GiftSetPage.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Login/OAuthRedirectPage.jsx
  src/pages/My/MyPage.jsx
  src/pages/Search/SearchPage.jsx
  src/styles/font.js
  src/styles/global.css
  src/styles/reset.css
Labels: UI 💄, Refactor ♻️, Feature ✨

#108 5주차 | 펀딩 개설 api연결
  package-lock.json
  package.json
  src/api/funding.js
  src/components/List/List.jsx
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/IndexPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
  src/pages/List/ListJoinPage.jsx
  src/pages/List/ListOpenPage.jsx
Labels: Feature ✨

#96 5주차 | readme 1차 작성
  README.md
Labels: Docs 📃

#103 5주차 | 홈페이지 api 연결, 선물 추가 페이지 데이터 연결
  src/api/calendar.js
  src/components/FundingInfo/FundingComment.jsx
  src/components/FundingInfo/FundingParticipants.jsx
  src/components/FundingInfo/FundingPercentage.jsx
  src/components/FundingInfo/GoWriteButton.jsx
  src/components/FundingInfo/PriceProgressBar.jsx
  src/components/FundingInfo/stylefunction.js
  src/components/Home/Calendar.jsx
  src/components/Home/CalendarFundingItem.jsx
  src/components/common/BottomBackgroundComponent.jsx
  src/components/common/ButtonComponent.jsx
  src/components/common/PasswordComponent.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/CompletePage.jsx
  src/pages/FundingOpen/GiftAddPage.jsx
  src/pages/Home/HomePage.jsx
Labels: Feature ✨

#114 6주차 | 라우팅, 로그인 관련 기능 추가 및 버그 수정, 그외 코드 리팩토링
  src/App.js
  src/api/friend.js
  src/api/funding.js
  src/api/notice.js
  src/api/review.js
  src/api/search.js
  src/api/user.js
  src/components/Friend/HorizontalCard.jsx
  src/components/Friend/VerticalCard.jsx
  src/components/FundingInfo/FundingPercentage.jsx
  src/components/FundingInfo/PriceProgressBar.jsx
  src/components/common/CompletePageComponent.jsx
  src/hoc/Auth.jsx
  src/hooks/useFormatDate.js
  src/pages/FundingJoin/CompletePage.jsx
  src/pages/FundingJoin/FundingJoinPage.jsx
  src/pages/FundingOpen/CompletePage.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Login/OAuthRedirectPage.jsx
  src/styles/global.css
Labels: Refactor ♻️, Feature ✨, Fix🔧

#113 6주차 | 알림페이지 수정 및 자잘한 오류들 수정
  src/pages/Edit/MessageEditPage.jsx
  src/pages/Edit/ReviewEditPage.jsx
  src/pages/Notification/NotificationPage.jsx
  src/pages/Search/SearchPage.jsx
Labels: Bug 🐞, Feature ✨

#109 6주차 | 결제 api 연결
  public/index.html
  src/api/payment.js
  src/components/FundingInfo/CongratsMessage.jsx
  src/components/FundingInfo/FundingPercentage.jsx
  src/components/FundingInfo/GoWriteButton.jsx
  src/components/FundingInfo/PriceProgressBar.jsx
  src/components/Home/Calendar.jsx
  src/components/common/ButtonComponent.jsx
  src/components/common/ScrollToTop.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/FundingJoinPage.jsx
  src/pages/FundingJoin/IndexPage.jsx
  src/pages/FundingJoin/PaymentLandingPage.jsx
  src/pages/List/ListOpenPage.jsx
Labels: Feature ✨

#115 6주차 | 알림 페이지 코드 리팩토링
  src/components/Notification/NotificationItem.jsx
  src/pages/Notification/NotificationPage.jsx
Labels: UI 💄, Refactor ♻️, Fix🔧

#117 6주차 | import 누락 버그 수정
  src/pages/FundingOpen/FundingSetPage.jsx
Labels: Fix🔧

#118 6주차 | import문 누락 버그 수정
  src/pages/FundingOpen/FundingSetPage.jsx
Labels: Fix🔧

#120 6주차 | 함수 훅 분리, tag 날짜 계산 수정
  src/components/FundingInfo/FundingPercentage.jsx
  src/hooks/useSortGiftData.js
  src/pages/FundingInfo/FundingInfoPage.jsx
Labels: Refactor ♻️, Fix🔧

#121 6주차 | 카카오 로그인 redirect_uri 배포 주소로 수정
  src/api/oauth.js
Labels: Fix🔧

#119 6주차 | 프로필사진 오류수정, 펀딩문구 수정
  src/components/Notification/NotificationItem.jsx
  src/pages/Edit/MessageEditPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
Labels: Refactor ♻️

#123 6주차 | default props, -제외
  src/components/common/PasswordComponent.jsx
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
Labels: Refactor ♻️

#124 6주차 | fix bugs
  src/api/oauth.js
  src/components/FundingInfo/FundingPercentage.jsx
  src/components/Notification/NotificationItem.jsx
  src/components/common/PasswordComponent.jsx
  src/hooks/useSortGiftData.js
  src/pages/Edit/MessageEditPage.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
Labels: Refactor ♻️, Fix🔧

#128 6주차 | 에러 처리 로직 추가
  src/api/api.js
  src/api/oauth.js
  src/components/common/ToastComponent.jsx
  src/hoc/Auth.jsx
  src/pages/Friend/FriendPage.jsx
  src/pages/Login/OAuthRedirectPage.jsx
  src/pages/Tutorial/TutorialPage.jsx
Labels: UI 💄, Refactor ♻️, Feature ✨

#125 6주차 | QA테스트 오류 수정
  src/components/FundingInfo/FundingParticipants.jsx
  src/components/FundingInfo/GoWriteButton.jsx
  src/components/Home/Calendar.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/List/ListOpenPage.jsx
Labels: Fix🔧

#126 6주차 | 알림 글자 오류, 프로필사진 오류 수정, 선물후기 CREATE 오류 수정, 새로고침 코드 추가
  src/pages/Edit/MessageEditPage.jsx
  src/pages/Edit/ReviewEditPage.jsx
  src/pages/Notification/NotificationPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
  src/pages/Search/SearchPage.jsx
Labels: Refactor ♻️, Fix🔧

#129 6주차 | 모바일 결제 오류 수정
  src/pages/FundingJoin/FundingJoinPage.jsx
  src/pages/FundingJoin/IndexPage.jsx
  src/pages/FundingJoin/PaymentLandingPage.jsx
Labels: Fix🔧

#127 6주차| 펀딩 개설 실패 시 alert 메시지 후 이동
  src/pages/FundingOpen/FundingSetPage.jsx
  src/pages/FundingOpen/IndexPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
Labels: Refactor ♻️

#134 6주차 | OAuthRedirectPage → 프로필 편집 페이지 → 홈 페이지 리다이렉트, 그외 퍼블리싱 및 코드 리팩토링
  _redirects
  src/components/Home/Calendar.jsx
  src/components/Notification/NotificationItem.jsx
  src/components/common/NotiItemComponent.jsx
  src/pages/Edit/MessageEditPage.jsx
  src/pages/Edit/ReviewEditPage.jsx
  src/pages/Friend/FriendPage.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/FundingJoinPage.jsx
  src/pages/FundingJoin/IndexPage.jsx
  src/pages/FundingJoin/PaymentLandingPage.jsx
  src/pages/FundingOpen/IndexPage.jsx
  src/pages/FundingOpen/PasswordSetPage.jsx
  src/pages/Login/OAuthRedirectPage.jsx
  src/pages/ProfileEdit/ProfileEditPage.jsx
  src/pages/Search/SearchPage.jsx
  src/styles/global.css
Labels: UI 💄, Refactor ♻️, Feature ✨

#133 6주차 | 에러 수정 및 페이지 이동 수정
  src/components/Home/Calendar.jsx
  src/pages/FundingInfo/FundingInfoPage.jsx
  src/pages/FundingJoin/CompletePage.jsx
  src/pages/FundingJoin/PaymentLandingPage.jsx
  src/pages/My/MyPage.jsx
Labels: Fix🔧

#132 6주차 | 튜토리얼 페이지 오타 수정
  src/pages/Edit/MessageEditPage.jsx
  src/pages/Tutorial/TutorialPage.jsx
  src/styles/reset.css
Labels: Refactor ♻️

#131 6주차| 💄ui: 색상 설정 추가, 친구 없을 때 default 0명
  src/pages/My/MyPage.jsx
Labels: UI 💄

#136 7주차 | 버그 리포트 이슈 템플릿 추가, github actions 브랜치 삭제 및 재생성 추가
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/branch-management.yml
Labels: Docs 📃, Settings ⚙️
